apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sslchar.fullname" . }}-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          resources:
            limits:
              cpu: 200m
              memory: 150M
            requests:
              cpu: 50m
              memory: 50M
          ports:
            - containerPort: 80
