apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "sslchar.fullname" . }}-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
    - hosts:
        - {{ .Values.host }}
      secretName: develop-mapineda48-com-tls
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "sslchar.fullname" . }}-service
                port:
                  name: http