apiVersion: v1
kind: Service
metadata:
  name: {{ include "sslchar.fullname" . }}-service
  annotations:
    nginx.ingress.kubernetes.io/ssl-services: "nginx-service"
spec:
  selector:
    app: nginx
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP
