version: "3.9"

services:
  storage.minio:
    environment:
      - "MINIO_ROOT_USER=${MINIO_ROOT_USER}"
      - "MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}"
      - "LETSENCRYPT_HOST=${STORAGE_HOST}"
      - "VIRTUAL_HOST=${STORAGE_HOST}"
      - "VIRTUAL_PORT=9000"
    command: server /data


# https://hub.docker.com/r/minio/console
  console.minio:
    environment:
      - "VIRTUAL_HOST=${MINIO_HOST}"
      - "LETSENCRYPT_HOST=${MINIO_HOST}"
      - "CONSOLE_MINIO_SERVER=https://${STORAGE_HOST}"

