version: "3.9"

services:
  storage.minio:
    image: minio/minio
    container_name: storage.minio
    environment:
      - "MINIO_ROOT_USER=minio"
      - "MINIO_ROOT_PASSWORD=minio12345"
      - "MINIO_BROWSER=off"
      - "VIRTUAL_HOST=storage.minio"
      - "VIRTUAL_PORT=80"
    volumes:
      - data:/data
    command: server --address :80 /data

  console.minio:
    image: minio/console:v0.25.0
    container_name: console.minio
    environment:
      - "CONSOLE_MINIO_SERVER=http://storage.minio"
      - "VIRTUAL_HOST=console.minio"
      - "VIRTUAL_PORT=9090"
    depends_on:
      - storage.minio
    command: server

volumes:
  data:

networks:
  default:
    name: reverse-proxy
  reverse-proxy:
    external: true
