# Docker drop-in to ensure it starts after blobfuse2
# This ensures certificates and volumes are available 
# when Docker attempts to mount container volumes.
[Unit]
After=mapineda48-blobfuse2.service
Requires=mapineda48-blobfuse2.service
