---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dev
spec:
  acme:
    # URL de Let's Encrypt para producción
    server: https://acme-v02.api.letsencrypt.org/directory
    email: $EMAIL_CLUSTER_ISSUER # reemplaza con tu email
    privateKeySecretRef:
      name: letsencrypt-dev-account-key
    solvers:
      - http01:
          ingress:
            class: nginx
